package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/NerdyGriffin/steam-switch-pro-templates/internal/template"
	"github.com/spf13/cobra"
)

func newScanValveCmd() *cobra.Command {
	var (
		steamPath string
		filter    string
	)
	cmd := &cobra.Command{
		Use:   "scan-valve",
		Short: "(maintainer) Hash Valve's controller_base/templates/*.vdf and emit Go source for ValveHashes.",
		Long: `scan-valve is a maintainer convenience. After a Steam client update,
run this on a machine that received the update to harvest current Valve
hashes for any templates we care about. The output is Go source ready
to paste into internal/template/valve.go's ValveHashes map.

By default scans every *.vdf in controller_base/templates/. Pass --filter
to narrow to a substring (e.g., --filter switch_pro to only emit Switch Pro
template hashes).

This is not generally useful to end users — it's documented here so that
contributors don't have to re-derive the workflow from scratch every time.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			install, err := resolveInstall(steamPath)
			if err != nil {
				return err
			}
			dir := install.TemplatesDir()
			entries, err := os.ReadDir(dir)
			if err != nil {
				return fmt.Errorf("read %s: %w", dir, err)
			}

			// Build a set of "this is ours" hashes so we don't accidentally
			// classify our own shipped template as a Valve release.
			ourHashes := map[string]string{}
			ours, err := template.All()
			if err != nil {
				return err
			}
			for _, t := range ours {
				ourHashes[t.Hash] = t.Filename
			}

			type pair struct{ name, hash string }
			var pairs []pair
			var skipped []string
			for _, e := range entries {
				if e.IsDir() || !strings.HasSuffix(e.Name(), ".vdf") {
					continue
				}
				if filter != "" && !strings.Contains(e.Name(), filter) {
					continue
				}
				body, err := os.ReadFile(filepath.Join(dir, e.Name()))
				if err != nil {
					return err
				}
				h := template.HashBytes(body)
				if owner, isOurs := ourHashes[h]; isOurs {
					skipped = append(skipped, fmt.Sprintf("%s (matches our embedded %s)", e.Name(), owner))
					continue
				}
				pairs = append(pairs, pair{e.Name(), h})
			}
			sort.Slice(pairs, func(i, j int) bool { return pairs[i].name < pairs[j].name })

			fmt.Printf("// Generated by `sspt scan-valve` on %s\n", time.Now().UTC().Format("2006-01-02"))
			fmt.Printf("// Steam install: %s\n", install.Root)
			fmt.Printf("// Update FirstSeen markers below to reflect the actual Steam client version.\n\n")
			fmt.Printf("var newValveHashes = map[string][]ValveRelease{\n")
			for _, p := range pairs {
				fmt.Printf("\t%q: {\n", p.name)
				fmt.Printf("\t\t{Hash: %q, FirstSeen: %q},\n", p.hash, "Steam client X.Y.Z ("+time.Now().UTC().Format("2006-01")+")")
				fmt.Printf("\t},\n")
			}
			fmt.Printf("}\n")
			fmt.Fprintf(os.Stderr, "\n  emitted %d entries\n", len(pairs))
			if len(skipped) > 0 {
				fmt.Fprintf(os.Stderr, "  skipped %d file(s) whose hash matches our own embedded templates:\n", len(skipped))
				for _, s := range skipped {
					fmt.Fprintf(os.Stderr, "    - %s\n", s)
				}
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&steamPath, "steam-path", "", "override Steam install location")
	cmd.Flags().StringVar(&filter, "filter", "", "only emit entries whose filename contains this substring")
	return cmd
}
